
#' List priors and traces
#'
#' @param propro_model A propro model, generated by create_propro
#'
#' @export
#'
list_priors <- function(propro_model) {
    propro_model$priors
}


#' @rdname list_priors
#' @export
list_traces <- function(propro_model) {
    propro_model$traces
}
