


#' Combine priors into one definition.
#'
#' Useful for specificing certain priors, e.g. Dirichlet.
#'
#' @param propro_model A propro model, generated by create_propro
#' @param start First number of beta to combine
#' @param end Last beta to combine
#'
#' @export
#'
combine_consecutive_priors <- function(propro_model, start, end) {
    priors <- propro_model$priors

    prior <- NULL
    nr <- NULL

    priors %>%
        mutate(nr = as.numeric(str_extract(prior, "[0-9]+"))) %>%
        filter(!(nr %in% start:end)) %>%
        add_row(prior = glue("beta[{start}:{end}]")) -> priors

    propro_model$priors <- priors

    return(propro_model)
}
