

#' Add additional variable to propro
#'
#' @param propro_model A propro model, generated by create_propro
#' @param name Name of the variable
#' @param value Definition of the variable. Should start with <-
#'
#' @export
#'
add_variable <- function(propro_model, name, value) {
    propro_model$params <- c(propro_model$params, name)

    if("extra" %in% names(propro_model)) {
        extra <- propro_model$extra

        extra %>%
            add_row(variable = name, specification = value)

        propro_model$extra <- extra

    } else {
        propro_model$extra <- tibble(variable = name, specification = value)
    }

    return(propro_model)


}
