


#' Add data to propro
#'
#' @param propro_model A propro model, generated by create_propro
#' @param name Name of data
#' @param value Value of data
#'
#' @export
#'
add_data <- function(propro_model, name, value) {

    if(name %in% names(propro_model$data)) {
        warning("Overwriting data elements")
    }
    propro_model$data[[name]] <- value

    return(propro_model)

}
