
#' Set prior
#'
#' @param propro_model A propro model, generated by create_propro
#' @param name Name of prior
#' @param value value of prior. Should start with <- or ~
#'
#' @export
#'
set_prior <- function(propro_model, name, value) {

    prior <- NULL
    specification <- NULL

    priors <- propro_model$priors

    if(!(name %in% priors$prior)) {
        stop("Prior not found")
    }
    if(!("specification") %in% colnames(priors)) {
        priors %>%
            mutate(specification = NA) -> priors
    }


    priors %>%
        mutate(specification = ifelse(prior == name, value, specification)) -> priors

    propro_model$priors <- priors
    return(propro_model)
}
