

#' Set complements of prior
#'
#' @param propro_model A propro model, generated by create_propro
#' @param n The amount of choices for which to set complements
#'
#' @export
#'
set_prior_complements <- function (propro_model, n) {

    prior <- NULL
    nr <- NULL
    choice_id <- NULL

    priors <- propro_model$priors

    priors %>%
        filter(!is.na(choice_id)) %>%
        group_by(choice_id) %>%
        mutate(nr = as.numeric(str_extract(prior, "[0-9]+"))) %>%
        mutate(count = n()) %>%
        filter(count == n) -> sel

    sel %>%
        filter(nr != max(nr)) %>%
        summarize(sum = paste0("(",paste(prior, collapse = " + "),")")) -> complement

    sel %>%
        filter(nr == max(nr)) %>%
        inner_join(complement) %>%
        mutate(specification = paste0("<- 1 - ",sum)) -> priors_to_set

    if(nrow(priors_to_set) > 0){
        for(i in 1:nrow(priors_to_set)) {
            propro_model %>%
                set_prior(priors_to_set$prior[i], priors_to_set$specification[i]) -> propro_model
        }
    }

    return(propro_model)


}
